apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: extended-resource-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extended-resource-controller
subjects:
  - kind: ServiceAccount
    name: extended-resource-controller
    namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: extended-resource-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - extendedresourceclaims
      - extendedresources
      - pods
      - nodes
    verbs:
      - watch
      - list
      - update
      - get
      - patch
      - create
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: extended-resource-controller
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extended-resource-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.app: extended-resource-controller
  template:
    metadata:
      name: extended-resource-controller
      labels:
        k8s.app: extended-resource-controller
    spec:
      serviceAccountName: extended-resource-controller
      containers:
        - image: extended-resource-controller:v0.1.0
          imagePullPolicy: IfNotPresent
          name: extended-resource-controller
          command:
            - /root/extended-resource-controller
            - --logtostderr=true
            - --v=4
